// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;  // ✅ CORREGIDO: Ahora retorna la configuración web
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 🔥 CONFIGURACIÓN WEB - AGREGADA (con tus valores de Firebase Console)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrPECH40anh1vzKH2Rg0woCW0_TajijUQ',
    appId: '1:473114283636:web:b6aad838c1d6c9d4178b21',
    messagingSenderId: '473114283636',
    projectId: 'iot-achocalla',
    authDomain: 'iot-achocalla.firebaseapp.com',
    storageBucket: 'iot-achocalla.firebasestorage.app',
    measurementId: 'G-500B119T10',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiwD76223CLxMMp_tg3gSe_Mha0L7l3lk',
    appId: '1:473114283636:ios:29c30ae5b0c3e353178b21',
    messagingSenderId: '473114283636',
    projectId: 'iot-achocalla',
    storageBucket: 'iot-achocalla.firebasestorage.app',
    iosClientId: '473114283636-a1iqbkf1rfnlb0a1i8fjn2gn2lgracp2.apps.googleusercontent.com',
    iosBundleId: 'com.achocalla.iotAchocalla',
  );

  // Configuraciones existentes (puedes dejarlas para otras plataformas)

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiwD76223CLxMMp_tg3gSe_Mha0L7l3lk',
    appId: '1:473114283636:ios:29c30ae5b0c3e353178b21',
    messagingSenderId: '473114283636',
    projectId: 'iot-achocalla',
    storageBucket: 'iot-achocalla.firebasestorage.app',
    iosClientId: '473114283636-a1iqbkf1rfnlb0a1i8fjn2gn2lgracp2.apps.googleusercontent.com',
    iosBundleId: 'com.achocalla.iotAchocalla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrPECH40anh1vzKH2Rg0woCW0_TajijUQ',
    appId: '1:473114283636:web:1c418663a780eea0178b21',
    messagingSenderId: '473114283636',
    projectId: 'iot-achocalla',
    authDomain: 'iot-achocalla.firebaseapp.com',
    storageBucket: 'iot-achocalla.firebasestorage.app',
    measurementId: 'G-Y36P7JG4XZ',
  );

}